--- #YAML:1.0
name:                Net-WhitePages
version:             1.01
abstract:            ~
license:             ~
author:              
    - darren chamberlain <darren@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    JSON:                          0.00
    LWP::Simple:                   0.00
    Params::Validate:              0.00
    URI:                           0.00
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
