--- #YAML:1.0
name:               Net-WhitePages
version:            1.05
abstract:           A Perl interface to the WhitePages.com API v1.0
author:
    - darren chamberlain <darren@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::Simple:       0.00
    Params::Validate:  0.00
    URI:               0.00
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
